"""Quick smoke test for the FailFixer core engine."""
import sys
import tempfile
from pathlib import Path

# Ensure the parent dir is on sys.path for package imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from failfixer.core.gcode_parser import GCodeParser
from failfixer.core.layer_mapper import LayerMapper
from failfixer.core.resume_generator import ResumeGenerator, ResumeConfig
from failfixer.core.validator import Validator
from failfixer.core.profiles import ProfileLoader
from failfixer.app.controller import Controller, ResumeRequest

# ---- Build a synthetic G-code file ----
SAMPLE = """\
; generated by TestSlicer
; thumbnail begin
; thumbnail end
M140 S60
M104 S200
M190 S60
M109 S200
G21
G90
M82
G28
G1 Z5 F3000
G1 X50 Y50 F3000
G92 E0
;LAYER:0
G1 Z0.300 F600
G1 X100 Y50 E10 F1200
G1 X100 Y100 E20
G1 X50 Y100 E30
G1 X50 Y50 E40
;LAYER:1
G1 Z0.500 F600
G1 X100 Y50 E50
G1 X100 Y100 E60
G1 X50 Y100 E70
G1 X50 Y50 E80
;LAYER:2
G1 Z0.700 F600
G1 X100 Y50 E90
G1 X100 Y100 E100
G1 X50 Y100 E110
G1 X50 Y50 E120
;LAYER:3
G1 Z0.900 F600
G1 X100 Y50 E130
G1 X100 Y100 E140
G1 X50 Y100 E150
G1 X50 Y50 E160
;LAYER:4
G1 Z1.100 F600
G1 X100 Y50 E170
G1 X100 Y100 E180
G1 X50 Y100 E190
G1 X50 Y50 E200
M140 S0
M104 S0
M84
"""

def test_parser():
    parser = GCodeParser()
    parsed = parser.parse_string(SAMPLE)
    assert parsed.detection_method == "comment_layer", f"Got: {parsed.detection_method}"
    assert len(parsed.layers) == 5, f"Expected 5 layers, got {len(parsed.layers)}"
    assert parsed.state.bed_temp == 60.0
    assert parsed.state.nozzle_temp == 200.0
    assert parsed.state.units == "G21"
    assert parsed.state.positioning == "G90"
    assert parsed.state.extruder_mode == "M82"
    print("  ✓ Parser: 5 layers, correct state detection")

def test_mapper():
    parser = GCodeParser()
    parsed = parser.parse_string(SAMPLE)
    mapper = LayerMapper(parsed.layers)
    
    # By layer number
    m = mapper.by_layer_number(2)
    assert m.layer.number == 2
    assert m.exact is True
    
    # By Z height (exact)
    m = mapper.by_z_height(0.700)
    assert m.layer.number == 2
    
    # By Z height (fuzzy within tolerance)
    m = mapper.by_z_height(0.710)
    assert m.layer.number == 2
    assert m.exact is False
    assert m.warning is not None
    
    # By Z height (out of tolerance)
    try:
        mapper.by_z_height(5.0)
        assert False, "Should have raised ValueError"
    except ValueError:
        pass
    
    print("  ✓ Mapper: layer/Z lookups, tolerance, out-of-range")

def test_generator():
    parser = GCodeParser()
    parsed = parser.parse_string(SAMPLE)
    mapper = LayerMapper(parsed.layers)
    match = mapper.by_layer_number(2)
    gen = ResumeGenerator()
    config = ResumeConfig(
        resume_layer=2,
        resume_z=0.700,
        bed_temp=60.0,
        nozzle_temp=200.0,
        safe_lift_mm=10.0,
        z_offset_mm=0.0,
    )
    lines = gen.generate(parsed, match, config)
    text = "\n".join(lines)
    assert "; === FailFixer Resume File ===" in text
    assert "G28 X Y" in text
    assert "G28 Z" not in text  # NEVER home Z
    assert ";LAYER:2" in text
    assert ";LAYER:1" not in text  # layers below removed
    assert ";LAYER:0" not in text
    assert "M140 S60" in text
    assert "M109 S200" in text
    assert "G92 Z" in text  # Set Z position (no homing)
    assert "M420 S1" in text  # Restore bed mesh
    assert "; === Resume Print from Layer 2 ===" in text
    print("  ✓ Generator: correct header, layers 0-1 removed, temps present")

def test_validator():
    parser = GCodeParser()
    parsed = parser.parse_string(SAMPLE)
    mapper = LayerMapper(parsed.layers)
    match = mapper.by_layer_number(2)
    gen = ResumeGenerator()
    config = ResumeConfig(
        resume_layer=2,
        resume_z=0.700,
        bed_temp=60.0,
        nozzle_temp=200.0,
        safe_lift_mm=10.0,
    )
    lines = gen.generate(parsed, match, config)
    v = Validator()
    result = v.validate(lines, resume_z=0.700, safe_lift_z=10.0)
    assert result.ok, f"Validation failed: {[e.message for e in result.errors]}"
    print(f"  ✓ Validator: passed ({len(result.warnings)} warnings)")

def test_profiles():
    loader = ProfileLoader()
    profile = loader.load()  # default
    assert profile.firmware == "marlin"
    assert profile.safe_lift_mm == 10.0
    print("  ✓ Profiles: default loaded correctly")

def test_controller():
    with tempfile.TemporaryDirectory() as tmpdir:
        # Write sample file
        gcode_path = Path(tmpdir) / "test_print.gcode"
        gcode_path.write_text(SAMPLE, encoding="utf-8")
        
        controller = Controller()
        request = ResumeRequest(
            input_path=gcode_path,
            resume_selector=3,  # layer 3
            z_offset_mm=0.0,
        )
        result = controller.run(request)
        
        assert result.output_path.exists()
        assert "resume_layer0003" in result.output_path.name
        assert result.validation.ok
        content = result.output_path.read_text(encoding="utf-8")
        assert "; === FailFixer Resume File ===" in content
        assert ";LAYER:3" in content
        assert "; Original file: test_print.gcode" in content
        print(f"  ✓ Controller: full pipeline, output={result.output_path.name}, {result.line_count} lines")
    
    # Test Z-height selector
    with tempfile.TemporaryDirectory() as tmpdir:
        gcode_path = Path(tmpdir) / "test_print.gcode"
        gcode_path.write_text(SAMPLE, encoding="utf-8")
        
        controller = Controller()
        request = ResumeRequest(
            input_path=gcode_path,
            resume_selector=0.9,  # Z height → should resolve to layer 3
        )
        result = controller.run(request)
        assert "resume_layer0003" in result.output_path.name
        print(f"  ✓ Controller: Z-height selector, resolved to layer 3")

def test_determinism():
    """Same inputs → same output (byte-for-byte)."""
    with tempfile.TemporaryDirectory() as tmpdir:
        gcode_path = Path(tmpdir) / "test_print.gcode"
        gcode_path.write_text(SAMPLE, encoding="utf-8")
        
        controller = Controller()
        request = ResumeRequest(input_path=gcode_path, resume_selector=2)
        
        r1 = controller.run(request)
        content1 = r1.output_path.read_bytes()
        
        # Run again (overwrite)
        r2 = controller.run(request)
        content2 = r2.output_path.read_bytes()
        
        assert content1 == content2, "Determinism check failed!"
        print("  ✓ Determinism: identical output on repeated runs")

if __name__ == "__main__":
    print("FailFixer Core Engine — Smoke Tests")
    print("=" * 45)
    test_parser()
    test_mapper()
    test_generator()
    test_validator()
    test_profiles()
    test_controller()
    test_determinism()
    print("=" * 45)
    print("All tests passed! ✓")
