"""Resume G-code generator for FailFixer.

Builds a new G-code file that:
  1. Injects a safe resume header (temps, home XY only, prime).
  2. Appends original G-code from the selected layer onward.
  3. NEVER auto-homes Z.
  4. Always lifts Z before any XY travel.
"""

from __future__ import annotations

from dataclasses import dataclass

from .gcode_parser import ParsedGCode, PrinterState
from .layer_mapper import LayerMatch


@dataclass
class ResumeConfig:
    """User-provided configuration for resume generation."""

    resume_layer: int
    resume_z: float
    bed_temp: float
    nozzle_temp: float
    safe_lift_mm: float = 10.0
    z_offset_mm: float = 0.0
    bed_mesh_cmd: str = "M420 S1"


class ResumeGenerator:
    """Generates resume G-code from parsed data + config."""

    def generate(
        self,
        parsed: ParsedGCode,
        match: LayerMatch,
        config: ResumeConfig,
    ) -> list[str]:
        """Return a list of G-code lines (without trailing newlines) for
        the resume file."""
        out: list[str] = []

        # --- Resume header (collision-safe startup sequence) ---
        effective_z = config.resume_z + config.z_offset_mm
        clearance_z = max(config.safe_lift_mm, effective_z + 5.0)

        # Derive original filename from parsed data if available
        original_filename = getattr(parsed, "source_filename", "unknown")

        out.append("; === FailFixer Resume File ===")
        out.append(f"; Original file: {original_filename}")
        out.append(f"; Resume Layer: {config.resume_layer}")
        out.append(f"; Resume Z: {config.resume_z:.3f}")
        out.append(f"; Z Offset: {config.z_offset_mm:.3f}")
        out.append("; Generated by FailFixer V1")
        out.append(";")
        out.append("; SAFETY: This file assumes the nozzle is at or near")
        out.append("; the top of the failed print when started.")
        out.append("")
        out.append("; --- Units & Mode ---")
        out.append("G21                        ; Millimeters")
        out.append("G90                        ; Absolute positioning")
        out.append("M82                        ; Absolute extrusion")
        out.append("")
        out.append("; --- Heat Up ---")
        out.append(f"M140 S{_fmt_temp(config.bed_temp)}           ; Start heating bed")
        out.append(f"M104 S{_fmt_temp(config.nozzle_temp)}        ; Start heating nozzle")
        out.append(f"M190 S{_fmt_temp(config.bed_temp)}           ; Wait for bed temp")
        out.append(f"M109 S{_fmt_temp(config.nozzle_temp)}        ; Wait for nozzle temp")
        out.append("")
        out.append("; --- Safe Homing (XY only) ---")
        out.append("; CRITICAL: Do NOT home Z — nozzle would crash into partial print")
        out.append("G28 X Y                    ; Home X and Y at corner")
        out.append("")
        out.append("; --- Set Z Position ---")
        out.append("; Tell firmware where Z is based on the failed layer height")
        out.append("; The nozzle should physically be at/near this height")
        out.append(f"G92 Z{effective_z:.3f}         ; Set current Z = resume height")
        out.append("")
        out.append("; --- Clearance Lift ---")
        out.append("; Move UP before any XY travel to avoid scraping the print")
        out.append(f"G1 Z{clearance_z:.3f} F300     ; Lift to safe clearance height")
        out.append("")
        out.append("; --- Restore Bed Mesh ---")
        out.append(f"{config.bed_mesh_cmd}      ; Enable bed mesh/compensation (skip G29 — probing risks collision)")
        out.append("")
        out.append("; --- Prime Nozzle ---")
        out.append("; Extrude at clearance height to get filament flowing")
        out.append("G1 X5 Y5 F3000             ; Move to front-left corner")
        out.append("G92 E0                     ; Reset extruder")
        out.append("G1 E8 F300                 ; Prime 8mm of filament (in the air, safe)")
        out.append("G1 E-0.5 F1800             ; Small retract to prevent ooze")
        out.append("G92 E0                     ; Reset extruder again")
        out.append("")
        out.append(f"; === Resume Print from Layer {config.resume_layer} ===")

        # --- Append original lines from selected layer onward ---
        layer = match.layer
        start = layer.start_line

        # Include all lines from layer start to end of file
        for line in parsed.lines[start:]:
            out.append(line)

        return out

    def generate_text(
        self,
        parsed: ParsedGCode,
        match: LayerMatch,
        config: ResumeConfig,
    ) -> str:
        """Convenience: return the resume G-code as a single string."""
        lines = self.generate(parsed, match, config)
        return "\n".join(lines) + "\n"


def _fmt_temp(temp: float) -> str:
    """Format a temperature: integer when whole, else one decimal."""
    if temp == int(temp):
        return str(int(temp))
    return f"{temp:.1f}"
